### ISSUE TITLE
free(): invalid size

### ISSUE THREAD

**Issue by JeremyJames** [nhristov/astro-compress#319]
Hi,

Even after upgrading to 2.2.17, I'm still having this issue. Any idea?

Thanks a lot

Astro v4.5.9
AstroCompress v2.2.17

**Comment by bngmnn** [comment]
Probably a duplicate of #316

**Comment by NikolaRHristov** [comment]
@bngmnn This should've been fixed in [v2.2.17](https://github.com/Playform/AstroCompress/releases/tag/v2.2.17)

@JeremyJames Can you share some of the images you're trying to compress ? I would like to debug.

**Comment by JeremyJames** [comment]
> @bngmnn This should've been fixed in [v2.2.17](https://github.com/Playform/AstroCompress/releases/tag/v2.2.17)
> 
> @JeremyJames Can you share some of the images you're trying to compress ? I would like to debug.

You are right, the problem is with a specific image. If I remove it, it works well in v2.2.17.

Here's the culprit:

![contact](https://github.com/Playform/AstroCompress/assets/1183341/2dd23db0-1be5-47c6-b841-fc627c927d5b)

Thanks for helping!

**Comment by NikolaRHristov** [comment]
We found the culprit in https://github.com/lovell/sharp/issues/3935#issuecomment-1881866341. Cache will be disabled in `v2.2.18`

**Comment by NikolaRHristov** [comment]
@JeremyJames Should be fixed in [v2.2.19](https://github.com/Playform/AstroCompress/releases/tag/v2.2.19)

**Comment by JeremyJames** [comment]
Hello! I'm still getting the error.

I did the following steps:
- Remove `node_modules`, `.astro` and `dist` folders
- Run `npm install`, astro compress v 2.2.19 got installed
- Run `npm build` :boom: free(): invalid size

Thanks for the help

**Comment by jurajkapsz** [comment]
I've recently noticed this as well with `v2.2.17` and `v2.2.19`: namely in `astro dev` mode, when an `astro image component` (eg [Astro Picture](https://docs.astro.build/en/guides/images/#picture-)) is part of the page content.
It looks like the `"_image"` [image endpoint](https://docs.astro.build/en/reference/configuration-reference/#imageendpoint) request causes the `free(): invalid size` crash.

`astro build` works fine.

**Comment by kristianfrost** [comment]
I second @jurajkapsz. I first tried removing all images. Then I tried commenting out the only <Picture /> element I have. And then I didn't get any errors — but no pictures 😆

**Comment by NikolaRHristov** [comment]
Can you share a bit of code on how you're running the `<Image />` component and `<Picture />` component maybe ? I'm trying all sorts of combinations but I can't get it to error. Maybe just an example and a few pictures will do.

**Comment by NikolaRHristov** [comment]
```ts
compress({
	Exclude: [(File: string) => File.indexOf("_image") !== -1],
});
```

And also does this 👆🏻 help ? 

```ts
compress({
	Exclude: [
		(File: string) => {
			console.log(File);
			return false;
		},
	],
});
```

And what is the output of 👆🏻 ?

**Comment by enricogallesio** [comment]
> I've recently noticed this as well with `v2.2.17` and `v2.2.19`: namely in `astro dev` mode, when an `astro image component` (eg [Astro Picture](https://docs.astro.build/en/guides/images/#picture-)) is part of the page content. It looks like the `"_image"` [image endpoint](https://docs.astro.build/en/reference/configuration-reference/#imageendpoint) request causes the `free(): invalid size` crash.
> 
> `astro build` works fine.

This is confirmed in my case. I got the same issue

**Comment by NikolaRHristov** [comment]
We don't compress in dev. `CompressAstro` hooks into the `astro:build:done` hook and only runs on build.

**Comment by jurajkapsz** [comment]
> We don't compress in dev. CompressAstro hooks into the astro:build:done hook and only runs on build.

Right, that's the interesting point, why it happens when `CompressAstro` is integrated. I'll make the tests you [mentioned](https://github.com/Playform/CompressAstro/issues/319#issuecomment-2026597220) earlier.

In the meantime I've conditioned its integration in my `astro config` like so (probably not the proper way, but it works):

```js
integrations: [
  import.meta.env.PROD &&
    (await import("astro-compress")).default({
      CSS: true,
      HTML: true,
      Image: true,
      JavaScript: true,
      SVG: true,
    }),
],
```

**Comment by NikolaRHristov** [comment]
So, there's a `PR` available https://github.com/withastro/astro/pull/10616 in favor of disabling the `sharp` `libvips` image cache. Maybe it helps. I hope it gets merged and this gets resolved soon.

**Comment by NikolaRHristov** [comment]
Can you try the latest `astro-compress` [v2.2.21](https://github.com/Playform/CompressAstro/releases/tag/AstroCompress%2Fv2.2.21) and `@playform/compress-astro` [v0.0.2](https://github.com/Playform/CompressAstro/releases/tag/CompressAstro%2Fv0.0.2) ? @JeremyJames @jurajkapsz @kristianfrost @enricogallesio

**Comment by jurajkapsz** [comment]
> Can you try the latest astro-compress v2.2.21 and @playform/compress-astro v0.0.2

`v2.2.21` didn't change anything. What is `compress-astro v0.0.2`?

**Comment by kristianfrost** [comment]
I get this error now:

```
npx astro add @playform/compress-astro
@playform/compress-astro doesn't appear to be an integration or an adapter. Find our official integrations at https://astro.build/integrations
```

**Comment by NikolaRHristov** [comment]
@jurajkapsz it's a deprecated package. In the future only `@playform/compress-astro` will remain or the new package `@playform/compress`. They're all the same in terms of functionality just have different names. See: https://github.com/Playform/CompressAstro/issues/324

**Comment by NikolaRHristov** [comment]
@kristianfrost I see, it seems that the integration must have an `astro-integration` keyword in its [package.json](https://github.com/Playform/CompressAstro/blob/Current/package.json) to be registered as an integration successfully by the `Astro` component. I removed it from the latest `@playform/compress-astro` [v0.0.2](https://github.com/Playform/CompressAstro/releases/tag/CompressAstro%2Fv0.0.2) and `astro-compress` [v2.2.21](https://github.com/Playform/CompressAstro/releases/tag/AstroCompress%2Fv2.2.21) as I didn't want to polute this page with https://astro.build/integrations/ two integrations that basically do the same thing internally.

You can add it to your `package.json` manually and it will still work. Just add:

```json
	"dependencies": {
		"@playform/compress-astro": "0.0.2"		
	},
```

to your `package.json` and import `compress()` from `@playform/compress-astro`.

See: https://github.com/Playform/CompressAstro#install-dependencies-manually

Thank you for the tip! It will be re-added to the latest version.

**Comment by jurajkapsz** [comment]
In reply to [this comment](https://github.com/Playform/CompressAstro/issues/319#issuecomment-2026597220):

> ```ts
> compress({
> 	Exclude: [(File: string) => File.indexOf("_image") !== -1],
> });
> ```
> 
> And also does this 👆🏻 help ?

No, it does not. Actually, to get the error, it seems, it is enough to just import the package into the astro config (I have `import compress from "astro-compress";`) without integrating anything.

In my `package.json`:
```
"dependencies": {
  "astro-compress": "^2.2.21",
}
```
---

> 
> ```ts
> compress({
> 	Exclude: [
> 		(File: string) => {
> 			console.log(File);
> 			return false;
> 		},
> 	],
> });
> ```
> 
> And what is the output of 👆🏻 ?

Nothing, I get the usual:
```
free(): invalid size
Aborted (core dumped)
```
---
For me, [this works fine](https://github.com/Playform/CompressAstro/issues/319#issuecomment-2027978924) (ie it does nothing on `dev` and compresses on `build`).

**Comment by NikolaRHristov** [comment]
@jurajkapsz Hm, interesting..

**Comment by NikolaRHristov** [comment]
It seems that importing two `sharp` instances causes this.

**Comment by NikolaRHristov** [comment]
@jurajkapsz @enricogallesio @JeremyJames @bngmnn `astro` `v4.5.15` just got released https://github.com/withastro/astro/blob/refs/heads/main/packages/astro/CHANGELOG.md#4515 with the `PR` merged - https://github.com/withastro/astro/pull/10616.

Can you give that a try with the latest `astro-compress` [v2.2.21](https://github.com/Playform/Compress/releases/tag/AstroCompress%2Fv2.2.21) or `@playform/compress-astro` [v0.0.2](https://github.com/Playform/Compress/releases/tag/CompressAstro%2Fv0.0.2) ?

**Comment by jurajkapsz** [comment]
No change after latest updates, the issue remains.

**Comment by NikolaRHristov** [comment]
Ok, there's one last resort I would like to try which might have been the culprit all this time https://github.com/Playform/Compress/blob/Current/Source/Function/Integration.ts#L203. Limiting / unlimiting the amount of memory used. I'll release a new version today with `unlimited` `false` see if that helps.

**Comment by JeremyJames** [comment]
> No change after latest updates, the issue remains.

Same here, still having the same error

**Comment by c3qo** [comment]
I used the `astro-compress 2.2.21` and `astro 4.5.15` on cloudflare, no luck.  The error is different but may be same rootcause?
```
10:01:44.414 | munmap_chunk(): invalid pointer
```

Seems the `astro-compress` depends on `sharp 0.33.3` and `astro` depends on `sharp ^0.32.6`, but the actual `sharp` installed into `node_modules` is `0.32.6`. 

As a workaround, overriding `sharp` version works. tested on cloudflare, the build passed.

```
  "overrides": {
    "sharp": "0.33.3"
  },
```

**Comment by NikolaRHristov** [comment]
`astro-compress` [v2.2.22](https://github.com/Playform/Compress/releases/tag/AstroCompress%2Fv2.2.22) and `@playform/compress` [v0.0.3](https://github.com/Playform/Compress/releases/tag/Compress%2Fv0.0.3) have been released with better error checking and `unlimited` `sharp` set to `false` in [Source/Function/Integration.ts](https://github.com/Playform/Compress/blob/e3849a199d40848e78eb6922e40dbf77d658b239/Source/Function/Integration.ts#L208-L228). Can you give that a try ? @JeremyJames @jurajkapsz @enricogallesio @kristianfrost

**Comment by NikolaRHristov** [comment]
> I used the `astro-compress 2.2.21` and `astro 4.5.15` on cloudflare, no luck. The error is different but may be same rootcause?
> 
> ```
> 10:01:44.414 | munmap_chunk(): invalid pointer
> ```
> 
> Seems the `astro-compress` depends on `sharp 0.33.3` and `astro` depends on `sharp ^0.32.6`, but the actual `sharp` installed into `node_modules` is `0.32.6`.
> 
> As a workaround, overriding `sharp` version works. tested on cloudflare, the build passed.
> 
> ```
>   "overrides": {
>     "sharp": "0.33.3"
>   },
> ```

This will be fixed by https://github.com/Playform/Compress/issues/329. You can track that issue there @c3qo.

**Comment by jurajkapsz** [comment]
> astro-compress v2.2.22 and @playform/compress v0.0.3 have been released with better error checking and unlimited sharp set to false in Source/Function/Integration.ts. Can you give that a try ?

Hi @NikolaRHristov , I switched to `@playform/compress v0.0.3`, and no change.

NB, there is a new warning showing up:

![image](https://github.com/Playform/Compress/assets/2209893/dac72e19-4b53-43ac-be4e-3d2b05df03d6)

**Comment by NikolaRHristov** [comment]
@jurajkapsz Yeah, I think it stems from the fact that `sharp` is imported at the main level in [Source/Function/Integration.ts](https://github.com/Playform/Compress/blob/f9a98930ac6458ec82078c58e0fe56767ecc355d/Source/Function/Integration.ts#L270-L272), which conflicts with the other `sharp` instance imported from `astro`.

If we import only where the `sharp` extension is used I think we can resolve this. A new version will be issued shortly. 

As a hotfix, does the new method of importing `Compress` work for you btw ?

```ts
export default {
	integrations: [(await import("@playform/compress")).default()],
};
```

As for this:

> NB, there is a new warning showing up:
> 
> ![image](https://private-user-images.githubusercontent.com/2209893/320959678-dac72e19-4b53-43ac-be4e-3d2b05df03d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2ODc1ODMsIm5iZiI6MTcxMjY4NzI4MywicGF0aCI6Ii8yMjA5ODkzLzMyMDk1OTY3OC1kYWM3MmUxOS00YjUzLTQzYWMtYmU0ZS0zZDJiMDVkZjAzZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDlUMTgyODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTMwYzc5OGRjOTAyN2UzMmJmM2JmOTdlOWZkYWZiZmYyNDc3ZWM3NWZlZWU2ZTFlNjI1MTI2MjRjZDAzM2Q1NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BHOaNQ7osBzevX9K2K7kjOYlNClECkYGYeSvaEAJzCc)

I'll work on a solution.. `Node` really shouldn't be installing dependencies that are declared in `devDependencies` by default 😅

**Comment by jurajkapsz** [comment]
> As a hotfix, does the new method of importing `Compress` work for you btw ?
> 
> ```ts
> export default {
> 	integrations: [(await import("@playform/compress")).default()],
> };
> ```
> 

I think I have it like that in my config as of now, so I don't think so.
But I use the workaround I mentioned before and I am perfectly fine with that.

**Comment by kristianfrost** [comment]
Does anyone have a fix for this issue? I'm still getting this:

```
21:01:32.925	 generating optimized images 
21:01:32.938	munmap_chunk(): invalid pointer
21:01:32.951	Aborted
21:01:32.962	Failed: Error while executing user command. Exited with error code: 134
21:01:32.972	Failed: build command exited with code: 1
21:01:34.192	Failed: error occurred while running build command
```

**Comment by NikolaRHristov** [comment]
Should be fixed the latest `astro-compress` [v2.2.23](https://github.com/PlayForm/Compress/releases/tag/AstroCompress%2Fv2.2.23) and `@playform/compress` [v0.0.4](https://github.com/PlayForm/Compress/releases/tag/Compress%2Fv0.0.4)
